// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Srv                  string               `protobuf:"bytes,2,opt,name=srv,proto3" json:"srv,omitempty"`
	Event                string               `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	Data                 []byte               `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Active               bool                 `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetSrv() string {
	if m != nil {
		return m.Srv
	}
	return ""
}

func (m *Message) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Message) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type CreateReq struct {
	Srv                  string   `protobuf:"bytes,1,opt,name=srv,proto3" json:"srv,omitempty"`
	Event                string   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetSrv() string {
	if m != nil {
		return m.Srv
	}
	return ""
}

func (m *CreateReq) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *CreateReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (m *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(m, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResp struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResp) Reset()         { *m = DeleteResp{} }
func (m *DeleteResp) String() string { return proto.CompactTextString(m) }
func (*DeleteResp) ProtoMessage()    {}
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *DeleteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResp.Unmarshal(m, b)
}
func (m *DeleteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResp.Marshal(b, m, deterministic)
}
func (m *DeleteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResp.Merge(m, src)
}
func (m *DeleteResp) XXX_Size() int {
	return xxx_messageInfo_DeleteResp.Size(m)
}
func (m *DeleteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResp proto.InternalMessageInfo

func (m *DeleteResp) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type FindReq struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Srv                  string               `protobuf:"bytes,2,opt,name=srv,proto3" json:"srv,omitempty"`
	Event                string               `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	Data                 string               `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	CreatedFrom          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_from,json=createdFrom,proto3" json:"created_from,omitempty"`
	CreatedTo            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_to,json=createdTo,proto3" json:"created_to,omitempty"`
	Active               string               `protobuf:"bytes,7,opt,name=active,proto3" json:"active,omitempty"`
	Limit                int64                `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64                `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindReq) Reset()         { *m = FindReq{} }
func (m *FindReq) String() string { return proto.CompactTextString(m) }
func (*FindReq) ProtoMessage()    {}
func (*FindReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *FindReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindReq.Unmarshal(m, b)
}
func (m *FindReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindReq.Marshal(b, m, deterministic)
}
func (m *FindReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindReq.Merge(m, src)
}
func (m *FindReq) XXX_Size() int {
	return xxx_messageInfo_FindReq.Size(m)
}
func (m *FindReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindReq proto.InternalMessageInfo

func (m *FindReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FindReq) GetSrv() string {
	if m != nil {
		return m.Srv
	}
	return ""
}

func (m *FindReq) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *FindReq) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *FindReq) GetCreatedFrom() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedFrom
	}
	return nil
}

func (m *FindReq) GetCreatedTo() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTo
	}
	return nil
}

func (m *FindReq) GetActive() string {
	if m != nil {
		return m.Active
	}
	return ""
}

func (m *FindReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindReq) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type FindResp struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindResp) Reset()         { *m = FindResp{} }
func (m *FindResp) String() string { return proto.CompactTextString(m) }
func (*FindResp) ProtoMessage()    {}
func (*FindResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *FindResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResp.Unmarshal(m, b)
}
func (m *FindResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResp.Marshal(b, m, deterministic)
}
func (m *FindResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResp.Merge(m, src)
}
func (m *FindResp) XXX_Size() int {
	return xxx_messageInfo_FindResp.Size(m)
}
func (m *FindResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResp.DiscardUnknown(m)
}

var xxx_messageInfo_FindResp proto.InternalMessageInfo

func (m *FindResp) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type CountFindResp struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountFindResp) Reset()         { *m = CountFindResp{} }
func (m *CountFindResp) String() string { return proto.CompactTextString(m) }
func (*CountFindResp) ProtoMessage()    {}
func (*CountFindResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *CountFindResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountFindResp.Unmarshal(m, b)
}
func (m *CountFindResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountFindResp.Marshal(b, m, deterministic)
}
func (m *CountFindResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountFindResp.Merge(m, src)
}
func (m *CountFindResp) XXX_Size() int {
	return xxx_messageInfo_CountFindResp.Size(m)
}
func (m *CountFindResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CountFindResp.DiscardUnknown(m)
}

var xxx_messageInfo_CountFindResp proto.InternalMessageInfo

func (m *CountFindResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PublishReq struct {
	MsgId                int64    `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishReq) Reset()         { *m = PublishReq{} }
func (m *PublishReq) String() string { return proto.CompactTextString(m) }
func (*PublishReq) ProtoMessage()    {}
func (*PublishReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *PublishReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishReq.Unmarshal(m, b)
}
func (m *PublishReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishReq.Marshal(b, m, deterministic)
}
func (m *PublishReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishReq.Merge(m, src)
}
func (m *PublishReq) XXX_Size() int {
	return xxx_messageInfo_PublishReq.Size(m)
}
func (m *PublishReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishReq.DiscardUnknown(m)
}

var xxx_messageInfo_PublishReq proto.InternalMessageInfo

func (m *PublishReq) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

type PublishResult struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MsgId                int64                `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PublishResult) Reset()         { *m = PublishResult{} }
func (m *PublishResult) String() string { return proto.CompactTextString(m) }
func (*PublishResult) ProtoMessage()    {}
func (*PublishResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *PublishResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResult.Unmarshal(m, b)
}
func (m *PublishResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResult.Marshal(b, m, deterministic)
}
func (m *PublishResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResult.Merge(m, src)
}
func (m *PublishResult) XXX_Size() int {
	return xxx_messageInfo_PublishResult.Size(m)
}
func (m *PublishResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResult.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResult proto.InternalMessageInfo

func (m *PublishResult) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PublishResult) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *PublishResult) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type FindPublishReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MsgId                int64    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindPublishReq) Reset()         { *m = FindPublishReq{} }
func (m *FindPublishReq) String() string { return proto.CompactTextString(m) }
func (*FindPublishReq) ProtoMessage()    {}
func (*FindPublishReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *FindPublishReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindPublishReq.Unmarshal(m, b)
}
func (m *FindPublishReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindPublishReq.Marshal(b, m, deterministic)
}
func (m *FindPublishReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindPublishReq.Merge(m, src)
}
func (m *FindPublishReq) XXX_Size() int {
	return xxx_messageInfo_FindPublishReq.Size(m)
}
func (m *FindPublishReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindPublishReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindPublishReq proto.InternalMessageInfo

func (m *FindPublishReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FindPublishReq) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

type FindPublishResp struct {
	Results              []*PublishResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FindPublishResp) Reset()         { *m = FindPublishResp{} }
func (m *FindPublishResp) String() string { return proto.CompactTextString(m) }
func (*FindPublishResp) ProtoMessage()    {}
func (*FindPublishResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *FindPublishResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindPublishResp.Unmarshal(m, b)
}
func (m *FindPublishResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindPublishResp.Marshal(b, m, deterministic)
}
func (m *FindPublishResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindPublishResp.Merge(m, src)
}
func (m *FindPublishResp) XXX_Size() int {
	return xxx_messageInfo_FindPublishResp.Size(m)
}
func (m *FindPublishResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FindPublishResp.DiscardUnknown(m)
}

var xxx_messageInfo_FindPublishResp proto.InternalMessageInfo

func (m *FindPublishResp) GetResults() []*PublishResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*CreateReq)(nil), "message.CreateReq")
	proto.RegisterType((*GetReq)(nil), "message.GetReq")
	proto.RegisterType((*DeleteReq)(nil), "message.DeleteReq")
	proto.RegisterType((*DeleteResp)(nil), "message.DeleteResp")
	proto.RegisterType((*FindReq)(nil), "message.FindReq")
	proto.RegisterType((*FindResp)(nil), "message.FindResp")
	proto.RegisterType((*CountFindResp)(nil), "message.CountFindResp")
	proto.RegisterType((*PublishReq)(nil), "message.PublishReq")
	proto.RegisterType((*PublishResult)(nil), "message.PublishResult")
	proto.RegisterType((*FindPublishReq)(nil), "message.FindPublishReq")
	proto.RegisterType((*FindPublishResp)(nil), "message.FindPublishResp")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0xed, 0xc4, 0x8e, 0x27, 0x4d, 0x5a, 0xb6, 0xa5, 0x58, 0xe1, 0x62, 0x2d, 0x42, 0xb2,
	0x2a, 0x48, 0xaa, 0xf4, 0xd0, 0x22, 0xc4, 0x01, 0x82, 0x1a, 0x71, 0x40, 0x42, 0xa6, 0xf7, 0xca,
	0x8e, 0x37, 0xae, 0x25, 0x3b, 0x6b, 0xbc, 0xeb, 0x48, 0x7c, 0x02, 0x1f, 0xc0, 0x3f, 0xf0, 0x99,
	0xc8, 0xeb, 0xb5, 0xe3, 0x24, 0x16, 0x8a, 0xb8, 0xed, 0xec, 0xbc, 0x99, 0x79, 0xf3, 0x66, 0x06,
	0x86, 0x09, 0x61, 0xcc, 0x0b, 0xc9, 0x24, 0xcd, 0x28, 0xa7, 0xc8, 0x90, 0xe6, 0xf8, 0x7d, 0x18,
	0xf1, 0xa7, 0xdc, 0x9f, 0x2c, 0x69, 0x32, 0x0d, 0x69, 0xec, 0xad, 0xc3, 0xa9, 0x40, 0xf8, 0xf9,
	0x6a, 0x9a, 0xf2, 0x9f, 0x29, 0x61, 0x53, 0x1e, 0x25, 0x84, 0x71, 0x2f, 0x49, 0xb7, 0xaf, 0x32,
	0x0b, 0xfe, 0xa3, 0x80, 0xf1, 0xb5, 0x4c, 0x84, 0x46, 0xa0, 0x46, 0x81, 0xa5, 0xd8, 0x8a, 0xa3,
	0xb9, 0x6a, 0x14, 0xa0, 0x33, 0xd0, 0x58, 0xb6, 0xb1, 0x54, 0x5b, 0x71, 0x4c, 0xb7, 0x78, 0xa2,
	0x0b, 0xe8, 0x91, 0x0d, 0x59, 0x73, 0x4b, 0x13, 0x7f, 0xa5, 0x81, 0x10, 0x74, 0x03, 0x8f, 0x7b,
	0x56, 0xd7, 0x56, 0x9c, 0x13, 0x57, 0xbc, 0xd1, 0x3b, 0x80, 0x65, 0x46, 0x3c, 0x4e, 0x82, 0x47,
	0x8f, 0x5b, 0x3d, 0x5b, 0x71, 0x06, 0xb3, 0xf1, 0x24, 0xa4, 0x34, 0x8c, 0x65, 0x03, 0x7e, 0xbe,
	0x9a, 0x3c, 0x54, 0x6c, 0x5c, 0x53, 0xa2, 0x3f, 0x72, 0x74, 0x09, 0xba, 0xb7, 0xe4, 0xd1, 0x86,
	0x58, 0xba, 0xad, 0x38, 0x7d, 0x57, 0x5a, 0x78, 0x01, 0xe6, 0x5c, 0x80, 0x5c, 0xf2, 0xa3, 0xe2,
	0xa6, 0xb4, 0x70, 0x53, 0xdb, 0xb8, 0x69, 0x5b, 0x6e, 0xd8, 0x02, 0x7d, 0x41, 0x78, 0x91, 0x65,
	0xaf, 0x63, 0xfc, 0x12, 0xcc, 0xcf, 0x24, 0x26, 0x65, 0x89, 0x7d, 0x27, 0x06, 0xa8, 0x9c, 0x2c,
	0x2d, 0xca, 0x6d, 0xbc, 0x38, 0x27, 0x02, 0xd0, 0x77, 0x4b, 0x03, 0xff, 0x56, 0xc1, 0xb8, 0x8f,
	0xd6, 0x41, 0x4b, 0xfc, 0x7f, 0xc9, 0x69, 0x4a, 0x39, 0x3f, 0xc0, 0x49, 0x25, 0xe7, 0x2a, 0xa3,
	0xc9, 0x11, 0x82, 0x0e, 0x24, 0xfe, 0x3e, 0xa3, 0x49, 0x73, 0x1a, 0x9c, 0x0a, 0x59, 0x8f, 0x9b,
	0xc6, 0x03, 0x6d, 0x4c, 0xc3, 0x10, 0x7c, 0xa4, 0x55, 0x70, 0x8f, 0xa3, 0x24, 0xe2, 0x56, 0x5f,
	0x34, 0x58, 0x1a, 0x05, 0x9a, 0xae, 0x56, 0x8c, 0x70, 0xcb, 0x14, 0xdf, 0xd2, 0xc2, 0x77, 0xd0,
	0x2f, 0x65, 0x61, 0x29, 0x7a, 0x03, 0x7d, 0xb9, 0xba, 0xcc, 0x52, 0x6c, 0xcd, 0x19, 0xcc, 0xce,
	0x26, 0xd5, 0x6a, 0xcb, 0x55, 0x74, 0x6b, 0x04, 0x7e, 0x0d, 0xc3, 0x39, 0xcd, 0xd7, 0xbc, 0x0e,
	0xbf, 0x80, 0x1e, 0xa7, 0xdc, 0x8b, 0xa5, 0xb2, 0xa5, 0x81, 0x5f, 0x01, 0x7c, 0xcb, 0xfd, 0x38,
	0x62, 0x4f, 0x85, 0xf4, 0xcf, 0x41, 0x4f, 0x58, 0xf8, 0x58, 0xcb, 0xdf, 0x4b, 0x58, 0xf8, 0x25,
	0xc0, 0x3e, 0x0c, 0x6b, 0x10, 0xcb, 0x63, 0x7e, 0x30, 0xa2, 0x6d, 0x9c, 0xda, 0x88, 0x43, 0x57,
	0xa0, 0x72, 0x26, 0x86, 0xf4, 0x6f, 0xd9, 0x54, 0xce, 0xf0, 0x2d, 0x8c, 0x0a, 0xaa, 0x0d, 0x32,
	0xc7, 0x15, 0xc1, 0x73, 0x38, 0xdd, 0x09, 0x64, 0x29, 0xba, 0x06, 0x23, 0x13, 0x44, 0x2b, 0xa1,
	0x2e, 0x6b, 0xa1, 0x76, 0xfa, 0x70, 0x2b, 0xd8, 0xec, 0x97, 0x06, 0x23, 0xa9, 0xe1, 0x77, 0x92,
	0x6d, 0xa2, 0x25, 0x41, 0xd7, 0xa0, 0x97, 0x67, 0x83, 0x50, 0x1d, 0x5d, 0xdf, 0xd1, 0xf8, 0x40,
	0x7a, 0xdc, 0x41, 0x57, 0xa0, 0x2d, 0x08, 0x47, 0xa7, 0xb5, 0xab, 0xbc, 0x96, 0x56, 0xec, 0x0d,
	0xe8, 0xe5, 0x51, 0x34, 0xb2, 0xd7, 0x27, 0x34, 0x3e, 0x3f, 0xf8, 0x63, 0x29, 0xee, 0xa0, 0xb7,
	0xd0, 0x2d, 0x5a, 0x45, 0xdb, 0x84, 0xf2, 0x66, 0xc6, 0xcf, 0xf6, 0x7e, 0x04, 0xfc, 0x16, 0xcc,
	0x7a, 0x05, 0x5a, 0x62, 0xb6, 0xa2, 0xec, 0x2c, 0x0a, 0xee, 0xa0, 0x3b, 0x30, 0xa4, 0x4e, 0xe8,
	0xfc, 0x50, 0xb9, 0x66, 0xe4, 0x8e, 0x9c, 0xb8, 0x83, 0x3e, 0xc1, 0xa0, 0x31, 0x0c, 0xf4, 0x62,
	0xa7, 0x68, 0x23, 0x83, 0xd5, 0xee, 0x28, 0xaa, 0xfb, 0xba, 0xd8, 0x90, 0x9b, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x5c, 0x0a, 0x40, 0xc2, 0xb8, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageServiceClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Message, error)
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*Message, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error)
	Find(ctx context.Context, in *FindReq, opts ...grpc.CallOption) (*FindResp, error)
	CountFind(ctx context.Context, in *FindReq, opts ...grpc.CallOption) (*CountFindResp, error)
	Publish(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResult, error)
	FindPublish(ctx context.Context, in *FindPublishReq, opts ...grpc.CallOption) (*FindPublishResp, error)
}

type messageServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessageServiceClient(cc *grpc.ClientConn) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/message.MessageService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/message.MessageService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error) {
	out := new(DeleteResp)
	err := c.cc.Invoke(ctx, "/message.MessageService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) Find(ctx context.Context, in *FindReq, opts ...grpc.CallOption) (*FindResp, error) {
	out := new(FindResp)
	err := c.cc.Invoke(ctx, "/message.MessageService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) CountFind(ctx context.Context, in *FindReq, opts ...grpc.CallOption) (*CountFindResp, error) {
	out := new(CountFindResp)
	err := c.cc.Invoke(ctx, "/message.MessageService/CountFind", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) Publish(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResult, error) {
	out := new(PublishResult)
	err := c.cc.Invoke(ctx, "/message.MessageService/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) FindPublish(ctx context.Context, in *FindPublishReq, opts ...grpc.CallOption) (*FindPublishResp, error) {
	out := new(FindPublishResp)
	err := c.cc.Invoke(ctx, "/message.MessageService/FindPublish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
type MessageServiceServer interface {
	Create(context.Context, *CreateReq) (*Message, error)
	Get(context.Context, *GetReq) (*Message, error)
	Delete(context.Context, *DeleteReq) (*DeleteResp, error)
	Find(context.Context, *FindReq) (*FindResp, error)
	CountFind(context.Context, *FindReq) (*CountFindResp, error)
	Publish(context.Context, *PublishReq) (*PublishResult, error)
	FindPublish(context.Context, *FindPublishReq) (*FindPublishResp, error)
}

// UnimplementedMessageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (*UnimplementedMessageServiceServer) Create(ctx context.Context, req *CreateReq) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedMessageServiceServer) Get(ctx context.Context, req *GetReq) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedMessageServiceServer) Delete(ctx context.Context, req *DeleteReq) (*DeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedMessageServiceServer) Find(ctx context.Context, req *FindReq) (*FindResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (*UnimplementedMessageServiceServer) CountFind(ctx context.Context, req *FindReq) (*CountFindResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountFind not implemented")
}
func (*UnimplementedMessageServiceServer) Publish(ctx context.Context, req *PublishReq) (*PublishResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (*UnimplementedMessageServiceServer) FindPublish(ctx context.Context, req *FindPublishReq) (*FindPublishResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindPublish not implemented")
}

func RegisterMessageServiceServer(s *grpc.Server, srv MessageServiceServer) {
	s.RegisterService(&_MessageService_serviceDesc, srv)
}

func _MessageService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Find(ctx, req.(*FindReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_CountFind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).CountFind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/CountFind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).CountFind(ctx, req.(*FindReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Publish(ctx, req.(*PublishReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_FindPublish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPublishReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).FindPublish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MessageService/FindPublish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).FindPublish(ctx, req.(*FindPublishReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _MessageService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MessageService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _MessageService_Delete_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _MessageService_Find_Handler,
		},
		{
			MethodName: "CountFind",
			Handler:    _MessageService_CountFind_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _MessageService_Publish_Handler,
		},
		{
			MethodName: "FindPublish",
			Handler:    _MessageService_FindPublish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
